library(rstan)
library(loo)

rm(list=ls())

load("results-gi-plus-dbh-uncoupled.Rsave")
log_lik_gi_uncoupled <- extract_log_lik(fit, parameter_name="log_lik_gi")
log_lik_dbh_uncoupled <- extract_log_lik(fit, parameter_name="log_lik_dbh")

load("results-gi-plus-dbh.Rsave")
log_lik_gi_coupled <- extract_log_lik(fit, parameter_name="log_lik_gi")
log_lik_dbh_coupled <- extract_log_lik(fit, parameter_name="log_lik_dbh")

sink("model-comparison.txt")
cat("Growth Increment component\n")
loo_coupled <- loo(log_lik_gi_coupled)
loo_uncoupled <- loo(log_lik_gi_uncoupled)
cat("Coupled model\n")
print(loo_coupled)
cat("\nUncoupled model\n")
print(loo_uncoupled)
cat("model comparison (+ uncoupled favored, - coupled favored)\n")
print(compare(loo_coupled, loo_uncoupled), digits=3)

cat("\n\n")
cat("DBH component\n")
loo_coupled <- loo(log_lik_dbh_coupled)
loo_uncoupled <- loo(log_lik_dbh_uncoupled)
cat("Coupled model\n")
print(loo_coupled)
cat("\nUncoupled model\n")
print(loo_uncoupled)
cat("model comparison (+ uncoupled favored, - coupled favored)\n")
print(compare(loo_coupled, loo_uncoupled), digits=3)
sink()
